on: [push]

jobs:
  Test_Job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
<<<<<<< HEAD
      # To use this repository's private action, you must check out the repository
=======
>>>>>>> origin/feature/bootstrap
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test this action
        uses: ./
        with:
          access-token: ${{ secrets.CR_TOKEN }}
          source-charts-folder: 'test-charts'
          destination-repo: dave-mcconnell/helm-charts
          destination-charts-folder: 'charts'
